language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors

before_script:
  - mysql -u root
  - grant usage on *.* to djangouser@localhost identified by 'pass28577';
  - grant all privileges on *.* to djangouser@localhost;
  - exit

after_script:
  - mysql -e 'drop user djangouser'

script: python manage.py test login_user event



